logging:
    level:
        ROOT: INFO
        com.noobug: DEBUG
        org.springframework: INFO

spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    h2:
        console:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    mail:
        host: smtp.qq.com
        port: 465
        username: 1427762764@qq.com
        password: w321654

server:
    port: 8081